# -*- coding: utf-8 -*-
"""生成 formulas_extra.json：扩充通识经典方（示意组成，课程用）。"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "formulas_extra.json"

ROLE = {"君": "jun", "臣": "chen", "佐": "zuo", "使": "shi"}


def F(key, name, cat, principle, source, comps, desc=""):
    composition = []
    for herb_key, role_zh, dosage in comps:
        composition.append(
            {
                "herb_key": herb_key,
                "role": ROLE.get(role_zh, "zuo"),
                "dosage": dosage,
                "explanation_zh": f"{role_zh}药",
            }
        )
    return {
        "key": key,
        "slug": key.replace("_", "-"),
        "name_zh": name,
        "category": cat,
        "source_text_key": source,
        "treatment_principle": {"zh": principle, "en": ""},
        "composition": composition,
        "preparation_zh": "水煎服。",
        "description_zh": desc or f"{name}：{principle}。",
        "verification": {"status": "course-sketch"},
    }


# (key, name, category, principle, source, [(herb_key, role, dose), ...], desc)
RAW = [
    ("xiao_chai_hu_tang", "小柴胡汤", "和解剂", "和解少阳", "shang_han_lun",
     [("chai_hu", "君", "24g"), ("huang_qin", "臣", "9g"), ("ban_xia", "佐", "9g"),
      ("ren_shen", "佐", "9g"), ("sheng_jiang", "佐", "9g"), ("da_zao", "使", "4枚"), ("gan_cao", "使", "6g")]),
    ("da_chai_hu_tang", "大柴胡汤", "和解剂", "和解少阳，内泻热结", "shang_han_lun",
     [("chai_hu", "君", "24g"), ("huang_qin", "臣", "9g"), ("zhi_shi", "臣", "9g"),
      ("bai_shao", "佐", "9g"), ("ban_xia", "佐", "9g"), ("da_huang", "佐", "6g"),
      ("sheng_jiang", "使", "15g"), ("da_zao", "使", "4枚")]),
    ("si_ni_san", "四逆散", "和解剂", "透邪解郁，疏肝理脾", "shang_han_lun",
     [("chai_hu", "君", "6g"), ("zhi_shi", "臣", "6g"), ("bai_shao", "佐", "6g"), ("gan_cao", "使", "6g")]),
    ("xiao_cheng_qi_tang", "小承气汤", "泻下剂", "轻下热结", "shang_han_lun",
     [("da_huang", "君", "12g"), ("hou_po", "臣", "6g"), ("zhi_shi", "佐", "9g")]),
    ("da_cheng_qi_tang", "大承气汤", "泻下剂", "峻下热结", "shang_han_lun",
     [("da_huang", "君", "12g"), ("mang_xiao", "臣", "9g"), ("hou_po", "佐", "15g"), ("zhi_shi", "佐", "12g")]),
    ("tiao_wei_cheng_qi_tang", "调胃承气汤", "泻下剂", "缓下热结", "shang_han_lun",
     [("da_huang", "君", "12g"), ("mang_xiao", "臣", "9g"), ("gan_cao", "使", "6g")]),
    ("bai_hu_jia_ren_shen_tang", "白虎加人参汤", "清热剂", "清热益气生津", "shang_han_lun",
     [("shi_gao", "君", "30g"), ("zhi_mu", "臣", "9g"), ("ren_shen", "佐", "9g"),
      ("gan_cao", "使", "6g"), ("geng_mi", "使", "9g")]),
    ("zhu_ye_shi_gao_tang", "竹叶石膏汤", "清热剂", "清热生津，益气和胃", "shang_han_lun",
     [("dan_zhu_ye", "君", "9g"), ("shi_gao", "君", "30g"), ("ban_xia", "臣", "9g"),
      ("mai_dong", "佐", "15g"), ("ren_shen", "佐", "6g"), ("gan_cao", "使", "6g"), ("geng_mi", "使", "9g")]),
    ("huang_lian_jie_du_tang", "黄连解毒汤", "清热剂", "泻火解毒", "wai_tai_mi_yao",
     [("huang_lian", "君", "9g"), ("huang_qin", "臣", "6g"), ("huang_bai", "佐", "6g"), ("zhi_zi", "使", "9g")]),
    ("pu_ji_xiao_du_yin", "普济消毒饮", "清热剂", "清热解毒，疏风散邪", "dong_yuan_shi_xiao_fang",
     [("huang_qin", "君", "15g"), ("huang_lian", "君", "15g"), ("niu_bang_zi", "臣", "3g"),
      ("lian_qiao", "臣", "3g"), ("bo_he", "佐", "3g"), ("jiang_can", "佐", "2g"),
      ("xuan_shen", "佐", "6g"), ("ma_bo", "佐", "3g"), ("ban_lan_gen", "佐", "3g"),
      ("jie_geng", "佐", "6g"), ("gan_cao", "使", "6g"), ("chen_pi", "使", "6g"), ("chai_hu", "使", "6g"), ("sheng_ma", "使", "2g")]),
    ("dao_chi_san", "导赤散", "清热剂", "清心利水养阴", "xiao_er_yao_zheng_zhi_jue",
     [("sheng_di_huang", "君", "9g"), ("mu_tong", "臣", "9g"), ("dan_zhu_ye", "佐", "9g"), ("gan_cao", "使", "9g")]),
    ("long_dan_xie_gan_tang", "龙胆泻肝汤", "清热剂", "清泻肝胆实火湿热", "yi_fang_ji_jie",
     [("long_dan_cao", "君", "6g"), ("huang_qin", "臣", "9g"), ("zhi_zi", "臣", "9g"),
      ("ze_xie", "佐", "12g"), ("mu_tong", "佐", "9g"), ("che_qian_zi", "佐", "9g"),
      ("dang_gui", "佐", "3g"), ("sheng_di_huang", "佐", "9g"), ("chai_hu", "佐", "6g"), ("gan_cao", "使", "6g")]),
    ("zuo_jin_wan", "左金丸", "清热剂", "清泻肝火，降逆止呕", "dan_xi_xin_fa",
     [("huang_lian", "君", "6g"), ("wu_zhu_yu", "佐", "1g")]),
    ("qing_wei_san", "清胃散", "清热剂", "清胃凉血", "lan_shi_mi_cang",
     [("huang_lian", "君", "6g"), ("sheng_ma", "臣", "6g"), ("mu_dan_pi", "佐", "9g"),
      ("sheng_di_huang", "佐", "6g"), ("dang_gui", "使", "6g")]),
    ("yu_nu_jian", "玉女煎", "清热剂", "清胃滋阴", "jing_yue_quan_shu",
     [("shi_gao", "君", "15g"), ("shu_di_huang", "臣", "9g"), ("mai_dong", "佐", "6g"),
      ("zhi_mu", "佐", "5g"), ("niu_xi", "使", "5g")]),
    ("xie_bai_san", "泻白散", "清热剂", "清泻肺热，止咳平喘", "xiao_er_yao_zheng_zhi_jue",
     [("sang_bai_pi", "君", "15g"), ("di_gu_pi", "臣", "15g"), ("gan_cao", "使", "3g"), ("geng_mi", "使", "9g")]),
    ("wei_jing_tang", "苇茎汤", "清热剂", "清肺化痰，逐瘀排脓", "bei_ji_qian_jin_yao_fang",
     [("lu_gen", "君", "30g"), ("yi_yi_ren", "臣", "30g"), ("dong_gua_zi", "佐", "24g"), ("tao_ren", "佐", "9g")]),
    ("sang_ju_yin", "桑菊饮", "解表剂", "疏风清热，宣肺止咳", "wen_bing_tiao_bian",
     [("sang_ye", "君", "7.5g"), ("ju_hua", "君", "3g"), ("xing_ren", "臣", "6g"),
      ("lian_qiao", "臣", "5g"), ("bo_he", "佐", "2.5g"), ("jie_geng", "佐", "6g"),
      ("gan_cao", "使", "2.5g"), ("lu_gen", "使", "6g")]),
    ("ma_xing_shi_gan_tang", "麻杏石甘汤", "解表剂", "辛凉宣肺，清热平喘", "shang_han_lun",
     [("ma_huang", "君", "9g"), ("shi_gao", "臣", "18g"), ("xing_ren", "佐", "9g"), ("gan_cao", "使", "6g")]),
    ("ge_gen_tang", "葛根汤", "解表剂", "发汗解表，升津舒经", "shang_han_lun",
     [("ge_gen", "君", "12g"), ("ma_huang", "臣", "9g"), ("gui_zhi", "臣", "6g"),
      ("bai_shao", "佐", "6g"), ("sheng_jiang", "佐", "9g"), ("da_zao", "使", "4枚"), ("gan_cao", "使", "6g")]),
    ("xiao_qing_long_tang", "小青龙汤", "解表剂", "解表散寒，温肺化饮", "shang_han_lun",
     [("ma_huang", "君", "9g"), ("gui_zhi", "臣", "9g"), ("gan_jiang", "臣", "9g"),
      ("xi_xin", "佐", "3g"), ("wu_wei_zi", "佐", "3g"), ("bai_shao", "佐", "9g"),
      ("ban_xia", "佐", "9g"), ("gan_cao", "使", "6g")]),
    ("jiu_wei_qiang_huo_tang", "九味羌活汤", "解表剂", "发汗祛湿，兼清里热", "ci_shi_nan_zhi",
     [("qiang_huo", "君", "6g"), ("fang_feng", "臣", "6g"), ("cang_zhu", "臣", "6g"),
      ("xi_xin", "佐", "2g"), ("chuan_xiong", "佐", "3g"), ("bai_zhi", "佐", "3g"),
      ("sheng_di_huang", "佐", "3g"), ("huang_qin", "佐", "3g"), ("gan_cao", "使", "3g")]),
    ("xiang_su_san", "香苏散", "解表剂", "疏散风寒，理气和中", "tai_ping_hui_min_he_ji_ju_fang",
     [("xiang_fu", "君", "6g"), ("zi_su_ye", "臣", "6g"), ("chen_pi", "佐", "3g"), ("gan_cao", "使", "3g")]),
    ("cuan_su_yin", "葱豉汤", "解表剂", "通阳发汗", "zhou_hou_bei_ji_fang",
     [("cong_bai", "君", "3茎"), ("dan_dou_chi", "臣", "9g")]),
    ("sheng_mai_san", "生脉散", "补益剂", "益气生津，敛阴止汗", "yi_xue_qi_yuan",
     [("ren_shen", "君", "9g"), ("mai_dong", "臣", "9g"), ("wu_wei_zi", "佐", "6g")]),
    ("si_jun_zi_jia_chen_pi", "异功散", "补益剂", "益气健脾，行气化滞", "xiao_er_yao_zheng_zhi_jue",
     [("ren_shen", "君", "6g"), ("bai_zhu", "臣", "6g"), ("fu_ling", "佐", "6g"),
      ("gan_cao", "使", "3g"), ("chen_pi", "佐", "3g")]),
    ("liu_jun_zi_tang", "六君子汤", "补益剂", "益气健脾，燥湿化痰", "yi_xue_zheng_chuan",
     [("ren_shen", "君", "9g"), ("bai_zhu", "臣", "9g"), ("fu_ling", "佐", "9g"),
      ("gan_cao", "使", "6g"), ("chen_pi", "佐", "6g"), ("ban_xia", "佐", "9g")]),
    ("xiang_sha_liu_jun_zi_tang", "香砂六君子汤", "补益剂", "益气健脾，行气化痰", "gu_jin_ming_yi_fang_lun",
     [("ren_shen", "君", "9g"), ("bai_zhu", "臣", "9g"), ("fu_ling", "佐", "9g"),
      ("gan_cao", "使", "6g"), ("chen_pi", "佐", "6g"), ("ban_xia", "佐", "9g"),
      ("mu_xiang", "佐", "6g"), ("sha_ren", "佐", "6g")]),
    ("shen_ling_bai_zhu_san", "参苓白术散", "补益剂", "益气健脾，渗湿止泻", "tai_ping_hui_min_he_ji_ju_fang",
     [("ren_shen", "君", "9g"), ("fu_ling", "臣", "9g"), ("bai_zhu", "臣", "9g"),
      ("shan_yao", "佐", "9g"), ("lian_zi", "佐", "6g"), ("bai_bian_dou", "佐", "9g"),
      ("yi_yi_ren", "佐", "6g"), ("sha_ren", "佐", "3g"), ("jie_geng", "使", "3g"), ("gan_cao", "使", "6g")]),
    ("dang_gui_bu_xue_tang", "当归补血汤", "补益剂", "补气生血", "nei_wai_shang_bian_huo_lun",
     [("huang_qi", "君", "30g"), ("dang_gui", "臣", "6g")]),
    ("gui_pi_tang", "归脾汤", "补益剂", "益气补血，健脾养心", "ji_sheng_fang",
     [("huang_qi", "君", "12g"), ("long_yan_rou", "君", "12g"), ("ren_shen", "臣", "6g"),
      ("bai_zhu", "臣", "9g"), ("dang_gui", "佐", "9g"), ("fu_ling", "佐", "9g"),
      ("suan_zao_ren", "佐", "9g"), ("yuan_zhi", "佐", "6g"), ("mu_xiang", "佐", "6g"),
      ("gan_cao", "使", "3g"), ("sheng_jiang", "使", "3片"), ("da_zao", "使", "3枚")]),
    ("zhi_gan_cao_tang", "炙甘草汤", "补益剂", "益气滋阴，通阳复脉", "shang_han_lun",
     [("gan_cao", "君", "12g"), ("sheng_di_huang", "君", "30g"), ("ren_shen", "臣", "6g"),
      ("gui_zhi", "臣", "9g"), ("mai_dong", "佐", "9g"), ("e_jiao", "佐", "6g"),
      ("huo_ma_ren", "佐", "9g"), ("sheng_jiang", "使", "9g"), ("da_zao", "使", "10枚")]),
    ("ba_zhen_tang", "八珍汤", "补益剂", "益气补血", "rui_zhu_tang_jing_yan_fang",
     [("ren_shen", "君", "9g"), ("bai_zhu", "臣", "9g"), ("fu_ling", "佐", "9g"),
      ("gan_cao", "使", "5g"), ("dang_gui", "君", "9g"), ("chuan_xiong", "臣", "6g"),
      ("bai_shao", "佐", "9g"), ("shu_di_huang", "佐", "12g")]),
    ("shi_quan_da_bu_tang", "十全大补汤", "补益剂", "温补气血", "tai_ping_hui_min_he_ji_ju_fang",
     [("ren_shen", "君", "9g"), ("bai_zhu", "臣", "9g"), ("fu_ling", "佐", "9g"),
      ("gan_cao", "使", "5g"), ("dang_gui", "君", "9g"), ("chuan_xiong", "臣", "6g"),
      ("bai_shao", "佐", "9g"), ("shu_di_huang", "佐", "12g"), ("huang_qi", "佐", "12g"), ("rou_gui", "佐", "3g")]),
    ("zhi_bai_di_huang_wan", "知柏地黄丸", "补益剂", "滋阴降火", "yi_zong_jin_jian",
     [("shu_di_huang", "君", "24g"), ("shan_zhu_yu", "臣", "12g"), ("shan_yao", "臣", "12g"),
      ("ze_xie", "佐", "9g"), ("mu_dan_pi", "佐", "9g"), ("fu_ling", "佐", "9g"),
      ("zhi_mu", "佐", "6g"), ("huang_bai", "佐", "6g")]),
    ("qi_ju_di_huang_wan", "杞菊地黄丸", "补益剂", "滋肾养肝明目", "yi_ji",
     [("shu_di_huang", "君", "24g"), ("shan_zhu_yu", "臣", "12g"), ("shan_yao", "臣", "12g"),
      ("ze_xie", "佐", "9g"), ("mu_dan_pi", "佐", "9g"), ("fu_ling", "佐", "9g"),
      ("gou_qi_zi", "佐", "9g"), ("ju_hua", "佐", "9g")]),
    ("du_qi_wan", "都气丸", "补益剂", "滋肾纳气", "yi_zong_ji_ren_bian",
     [("shu_di_huang", "君", "24g"), ("shan_zhu_yu", "臣", "12g"), ("shan_yao", "臣", "12g"),
      ("ze_xie", "佐", "9g"), ("mu_dan_pi", "佐", "9g"), ("fu_ling", "佐", "9g"), ("wu_wei_zi", "佐", "6g")]),
    ("mai_wei_di_huang_wan", "麦味地黄丸", "补益剂", "滋补肺肾", "shou_shi_bao_yuan",
     [("shu_di_huang", "君", "24g"), ("shan_zhu_yu", "臣", "12g"), ("shan_yao", "臣", "12g"),
      ("ze_xie", "佐", "9g"), ("mu_dan_pi", "佐", "9g"), ("fu_ling", "佐", "9g"),
      ("mai_dong", "佐", "9g"), ("wu_wei_zi", "佐", "6g")]),
    ("you_gui_wan", "右归丸", "补益剂", "温补肾阳，填精益髓", "jing_yue_quan_shu",
     [("shu_di_huang", "君", "24g"), ("shan_zhu_yu", "臣", "9g"), ("gou_qi_zi", "臣", "9g"),
      ("tu_si_zi", "佐", "12g"), ("du_zhong", "佐", "12g"), ("dang_gui", "佐", "9g"),
      ("rou_gui", "佐", "6g"), ("fu_zi", "佐", "6g"), ("lu_jiao_jiao", "佐", "12g"), ("shan_yao", "使", "12g")]),
    ("zuo_gui_wan", "左归丸", "补益剂", "滋阴补肾，填精益髓", "jing_yue_quan_shu",
     [("shu_di_huang", "君", "24g"), ("shan_zhu_yu", "臣", "12g"), ("gou_qi_zi", "臣", "12g"),
      ("shan_yao", "佐", "12g"), ("niu_xi", "佐", "9g"), ("tu_si_zi", "佐", "12g"),
      ("lu_jiao_jiao", "佐", "12g"), ("gui_ban_jiao", "佐", "12g")]),
    ("jin_gui_shen_qi_wan", "金匮肾气丸", "补益剂", "温补肾阳", "jin_gui_yao_lue",
     [("shu_di_huang", "君", "24g"), ("shan_zhu_yu", "臣", "12g"), ("shan_yao", "臣", "12g"),
      ("ze_xie", "佐", "9g"), ("mu_dan_pi", "佐", "9g"), ("fu_ling", "佐", "9g"),
      ("fu_zi", "佐", "3g"), ("gui_zhi", "佐", "3g")]),
    ("er_xian_tang", "二仙汤", "补益剂", "温肾阳，补肾精，泻相火", "xian_dai_jing_yan_fang",
     [("xian_mao", "君", "9g"), ("yin_yang_huo", "君", "9g"), ("ba_ji_tian", "臣", "9g"),
      ("huang_bai", "佐", "6g"), ("zhi_mu", "佐", "6g"), ("dang_gui", "使", "9g")]),
    ("si_ni_tang", "四逆汤", "温里剂", "回阳救逆", "shang_han_lun",
     [("fu_zi", "君", "15g"), ("gan_jiang", "臣", "9g"), ("gan_cao", "使", "6g")]),
    ("li_zhong_wan", "理中丸", "温里剂", "温中祛寒，补气健脾", "shang_han_lun",
     [("ren_shen", "君", "9g"), ("gan_jiang", "臣", "9g"), ("bai_zhu", "佐", "9g"), ("gan_cao", "使", "9g")]),
    ("wu_zhu_yu_tang", "吴茱萸汤", "温里剂", "温中补虚，降逆止呕", "shang_han_lun",
     [("wu_zhu_yu", "君", "9g"), ("ren_shen", "臣", "9g"), ("sheng_jiang", "佐", "18g"), ("da_zao", "使", "4枚")]),
    ("xiao_jian_zhong_tang", "小建中汤", "温里剂", "温中补虚，和里缓急", "shang_han_lun",
     [("yi_tang", "君", "30g"), ("gui_zhi", "臣", "9g"), ("bai_shao", "臣", "18g"),
      ("sheng_jiang", "佐", "9g"), ("da_zao", "使", "6枚"), ("gan_cao", "使", "6g")]),
    ("da_jian_zhong_tang", "大建中汤", "温里剂", "温中补虚，降逆止痛", "jin_gui_yao_lue",
     [("chuan_jiao", "君", "6g"), ("gan_jiang", "臣", "12g"), ("ren_shen", "佐", "6g"), ("yi_tang", "使", "30g")]),
    ("dang_gui_si_ni_tang", "当归四逆汤", "温里剂", "温经散寒，养血通脉", "shang_han_lun",
     [("dang_gui", "君", "12g"), ("gui_zhi", "臣", "9g"), ("bai_shao", "臣", "9g"),
      ("xi_xin", "佐", "3g"), ("tong_cao", "佐", "6g"), ("da_zao", "使", "8枚"), ("gan_cao", "使", "6g")]),
    ("yang_he_tang", "阳和汤", "温里剂", "温阳补血，散寒通滞", "wai_ke_zheng_zhi_quan_sheng_ji",
     [("shu_di_huang", "君", "30g"), ("rou_gui", "臣", "3g"), ("ma_huang", "佐", "2g"),
      ("lu_jiao_jiao", "佐", "9g"), ("bai_jie_zi", "佐", "6g"), ("jiang_tan", "佐", "2g"), ("gan_cao", "使", "3g")]),
    ("er_chen_tang", "二陈汤", "祛痰剂", "燥湿化痰，理气和中", "tai_ping_hui_min_he_ji_ju_fang",
     [("ban_xia", "君", "15g"), ("chen_pi", "臣", "15g"), ("fu_ling", "佐", "9g"), ("gan_cao", "使", "5g")]),
    ("wen_dan_tang", "温胆汤", "祛痰剂", "理气化痰，和胃利胆", "san_yin_ji_yi_bing_zheng_fang_lun",
     [("ban_xia", "君", "6g"), ("zhu_ru", "臣", "6g"), ("zhi_shi", "臣", "6g"),
      ("chen_pi", "佐", "9g"), ("fu_ling", "佐", "5g"), ("gan_cao", "使", "3g")]),
    ("qing_qi_hua_tan_wan", "清气化痰丸", "祛痰剂", "清热化痰，理气止咳", "yi_fang_kao",
     [("dan_nan_xing", "君", "45g"), ("huang_qin", "臣", "30g"), ("gua_lou_ren", "臣", "30g"),
      ("zhi_shi", "佐", "30g"), ("chen_pi", "佐", "30g"), ("fu_ling", "佐", "30g"),
      ("xing_ren", "佐", "30g"), ("ban_xia", "佐", "45g")]),
    ("bei_mu_gua_lou_san", "贝母瓜蒌散", "祛痰剂", "润肺清热，理气化痰", "yi_xue_xin_wu",
     [("chuan_bei_mu", "君", "5g"), ("gua_lou", "臣", "3g"), ("tian_hua_fen", "佐", "3g"),
      ("fu_ling", "佐", "3g"), ("ju_hong", "佐", "3g"), ("jie_geng", "使", "3g")]),
    ("san_zi_yang_qin_tang", "三子养亲汤", "祛痰剂", "降气快膈，化痰消食", "han_shi_yi_tong",
     [("bai_jie_zi", "君", "6g"), ("zi_su_zi", "臣", "9g"), ("lai_fu_zi", "佐", "9g")]),
    ("ban_xia_bai_zhu_tian_ma_tang", "半夏白术天麻汤", "祛痰剂", "燥湿化痰，平肝息风", "yi_xue_xin_wu",
     [("ban_xia", "君", "9g"), ("tian_ma", "君", "6g"), ("bai_zhu", "臣", "15g"),
      ("fu_ling", "佐", "6g"), ("chen_pi", "佐", "6g"), ("gan_cao", "使", "3g"),
      ("sheng_jiang", "使", "1片"), ("da_zao", "使", "2枚")]),
    ("zhi_sou_san", "止嗽散", "祛痰剂", "宣利肺气，疏风止咳", "yi_xue_xin_wu",
     [("jie_geng", "君", "9g"), ("jing_jie", "臣", "9g"), ("zi_wan", "臣", "9g"),
      ("bai_bu", "佐", "9g"), ("bai_qian", "佐", "9g"), ("chen_pi", "佐", "6g"), ("gan_cao", "使", "3g")]),
    ("ding_chuan_tang", "定喘汤", "祛痰剂", "宣肺降气，清热化痰", "she_sheng_zhong_miao_fang",
     [("bai_guo", "君", "9g"), ("ma_huang", "君", "9g"), ("zi_su_zi", "臣", "6g"),
      ("gan_cao", "使", "3g"), ("kuan_dong_hua", "佐", "9g"), ("xing_ren", "佐", "6g"),
      ("sang_bai_pi", "佐", "9g"), ("huang_qin", "佐", "6g"), ("ban_xia", "佐", "9g")]),
    ("wu_ling_san", "五苓散", "祛湿剂", "利水渗湿，温阳化气", "shang_han_lun",
     [("ze_xie", "君", "15g"), ("zhu_ling", "臣", "9g"), ("fu_ling", "臣", "9g"),
      ("bai_zhu", "佐", "9g"), ("gui_zhi", "使", "6g")]),
    ("zhu_ling_tang", "猪苓汤", "祛湿剂", "利水清热养阴", "shang_han_lun",
     [("zhu_ling", "君", "9g"), ("fu_ling", "臣", "9g"), ("ze_xie", "臣", "9g"),
      ("e_jiao", "佐", "9g"), ("hua_shi", "佐", "9g")]),
    ("fang_ji_huang_qi_tang", "防己黄芪汤", "祛湿剂", "益气祛风，健脾利水", "jin_gui_yao_lue",
     [("huang_qi", "君", "15g"), ("fang_ji", "臣", "12g"), ("bai_zhu", "佐", "9g"), ("gan_cao", "使", "6g")]),
    ("zhen_wu_tang", "真武汤", "祛湿剂", "温阳利水", "shang_han_lun",
     [("fu_zi", "君", "9g"), ("bai_zhu", "臣", "6g"), ("fu_ling", "臣", "9g"),
      ("bai_shao", "佐", "9g"), ("sheng_jiang", "使", "9g")]),
    ("shi_pi_yin", "实脾散", "祛湿剂", "温阳健脾，行气利水", "ji_sheng_fang",
     [("fu_zi", "君", "6g"), ("gan_jiang", "君", "6g"), ("fu_ling", "臣", "6g"),
      ("bai_zhu", "臣", "6g"), ("mu_gua", "佐", "6g"), ("hou_po", "佐", "6g"),
      ("mu_xiang", "佐", "6g"), ("da_fu_pi", "佐", "6g"), ("cao_guo", "佐", "6g"),
      ("gan_cao", "使", "3g"), ("sheng_jiang", "使", "5片"), ("da_zao", "使", "1枚")]),
    ("bi_xie_fen_qing_yin", "萆薢分清饮", "祛湿剂", "温暖下元，利湿化浊", "yang_shi_jia_cang_fang",
     [("bi_xie", "君", "12g"), ("yi_zhi_ren", "臣", "9g"), ("wu_yao", "佐", "9g"), ("shi_chang_pu", "使", "9g")]),
    ("san_ren_tang", "三仁汤", "祛湿剂", "宣畅气机，清利湿热", "wen_bing_tiao_bian",
     [("xing_ren", "君", "15g"), ("bai_kou_ren", "君", "6g"), ("yi_yi_ren", "君", "18g"),
      ("ban_xia", "臣", "9g"), ("hou_po", "臣", "6g"), ("tong_cao", "佐", "6g"),
      ("dan_zhu_ye", "佐", "6g"), ("hua_shi", "佐", "18g")]),
    ("gan_lu_xiao_du_dan", "甘露消毒丹", "祛湿剂", "利湿化浊，清热解毒", "wen_re_jing_wei",
     [("hua_shi", "君", "15g"), ("yin_chen", "君", "11g"), ("huang_qin", "臣", "10g"),
      ("shi_chang_pu", "佐", "6g"), ("chuan_bei_mu", "佐", "5g"), ("mu_tong", "佐", "5g"),
      ("huo_xiang", "佐", "4g"), ("she_gan", "佐", "4g"), ("lian_qiao", "佐", "4g"),
      ("bo_he", "使", "4g"), ("bai_kou_ren", "使", "4g")]),
    ("yin_chen_hao_tang", "茵陈蒿汤", "祛湿剂", "清热利湿退黄", "shang_han_lun",
     [("yin_chen", "君", "18g"), ("zhi_zi", "臣", "9g"), ("da_huang", "佐", "6g")]),
    ("ba_zheng_san", "八正散", "祛湿剂", "清热泻火，利水通淋", "tai_ping_hui_min_he_ji_ju_fang",
     [("che_qian_zi", "君", "9g"), ("qu_mai", "臣", "9g"), ("bian_xu", "臣", "9g"),
      ("hua_shi", "佐", "9g"), ("zhi_zi", "佐", "9g"), ("gan_cao", "使", "9g"),
      ("mu_tong", "佐", "9g"), ("da_huang", "佐", "9g")]),
    ("er_miao_san", "二妙散", "祛湿剂", "清热燥湿", "dan_xi_xin_fa",
     [("huang_bai", "君", "15g"), ("cang_zhu", "臣", "15g")]),
    ("san_miao_wan", "三妙丸", "祛湿剂", "清热燥湿", "yi_xue_zheng_chuan",
     [("huang_bai", "君", "15g"), ("cang_zhu", "臣", "15g"), ("niu_xi", "佐", "9g")]),
    ("ping_wei_san", "平胃散", "祛湿剂", "燥湿运脾，行气和胃", "tai_ping_hui_min_he_ji_ju_fang",
     [("cang_zhu", "君", "15g"), ("hou_po", "臣", "9g"), ("chen_pi", "佐", "9g"), ("gan_cao", "使", "6g")]),
    ("huo_xiang_zheng_qi_san", "藿香正气散", "祛湿剂", "解表化湿，理气和中", "tai_ping_hui_min_he_ji_ju_fang",
     [("huo_xiang", "君", "9g"), ("zi_su_ye", "臣", "6g"), ("bai_zhi", "臣", "6g"),
      ("ban_xia", "佐", "9g"), ("chen_pi", "佐", "6g"), ("bai_zhu", "佐", "9g"),
      ("hou_po", "佐", "6g"), ("fu_ling", "佐", "9g"), ("jie_geng", "佐", "6g"),
      ("da_fu_pi", "佐", "9g"), ("gan_cao", "使", "6g")]),
    ("bao_he_wan", "保和丸", "消食剂", "消食和胃", "dan_xi_xin_fa",
     [("shan_zha", "君", "18g"), ("shen_qu", "臣", "6g"), ("lai_fu_zi", "臣", "6g"),
      ("ban_xia", "佐", "9g"), ("chen_pi", "佐", "6g"), ("fu_ling", "佐", "9g"), ("lian_qiao", "佐", "6g")]),
    ("jian_pi_wan", "健脾丸", "消食剂", "健脾和胃，消食止泻", "zheng_zhi_zhun_sheng",
     [("bai_zhu", "君", "75g"), ("mu_xiang", "臣", "22g"), ("huang_lian", "臣", "22g"),
      ("gan_cao", "使", "22g"), ("fu_ling", "佐", "60g"), ("ren_shen", "佐", "45g"),
      ("shen_qu", "佐", "30g"), ("chen_pi", "佐", "30g"), ("sha_ren", "佐", "30g"),
      ("mai_ya", "佐", "30g"), ("shan_zha", "佐", "30g"), ("shan_yao", "佐", "30g")]),
    ("zhi_shi_dao_zhi_wan", "枳实导滞丸", "消食剂", "消导化积，清热祛湿", "nei_wai_shang_bian_huo_lun",
     [("da_huang", "君", "30g"), ("zhi_shi", "臣", "15g"), ("shen_qu", "佐", "15g"),
      ("fu_ling", "佐", "9g"), ("huang_qin", "佐", "9g"), ("huang_lian", "佐", "9g"),
      ("bai_zhu", "佐", "9g"), ("ze_xie", "使", "6g")]),
    ("yue_ju_wan", "越鞠丸", "理气剂", "行气解郁", "dan_xi_xin_fa",
     [("xiang_fu", "君", "6g"), ("chuan_xiong", "臣", "6g"), ("cang_zhu", "佐", "6g"),
      ("zhi_zi", "佐", "6g"), ("shen_qu", "佐", "6g")]),
    ("ban_xia_hou_po_tang", "半夏厚朴汤", "理气剂", "行气散结，降逆化痰", "jin_gui_yao_lue",
     [("ban_xia", "君", "12g"), ("hou_po", "臣", "9g"), ("fu_ling", "佐", "12g"),
      ("sheng_jiang", "佐", "9g"), ("zi_su_ye", "使", "6g")]),
    ("zhi_shi_xie_bai_gui_zhi_tang", "枳实薤白桂枝汤", "理气剂", "通阳散结，祛痰下气", "jin_gui_yao_lue",
     [("zhi_shi", "君", "12g"), ("hou_po", "臣", "12g"), ("xie_bai", "臣", "9g"),
      ("gui_zhi", "佐", "3g"), ("gua_lou", "佐", "12g")]),
    ("tian_tai_wu_yao_san", "天台乌药散", "理气剂", "行气疏肝，散寒止痛", "sheng_ji_zong_lu",
     [("wu_yao", "君", "12g"), ("mu_xiang", "臣", "6g"), ("xiao_hui_xiang", "臣", "6g"),
      ("qing_pi", "佐", "6g"), ("gao_liang_jiang", "佐", "6g"), ("bing_lang", "佐", "9g"), ("chuan_lian_zi", "使", "12g")]),
    ("nuan_gan_jian", "暖肝煎", "理气剂", "温补肝肾，行气止痛", "jing_yue_quan_shu",
     [("dang_gui", "君", "9g"), ("gou_qi_zi", "君", "9g"), ("xiao_hui_xiang", "臣", "6g"),
      ("rou_gui", "臣", "3g"), ("wu_yao", "佐", "6g"), ("chen_xiang", "佐", "3g"), ("fu_ling", "使", "6g")]),
    ("su_zi_jiang_qi_tang", "苏子降气汤", "理气剂", "降气平喘，祛痰止咳", "tai_ping_hui_min_he_ji_ju_fang",
     [("zi_su_zi", "君", "9g"), ("ban_xia", "臣", "9g"), ("dang_gui", "佐", "6g"),
      ("gan_cao", "使", "6g"), ("qian_hu", "佐", "6g"), ("hou_po", "佐", "6g"),
      ("rou_gui", "佐", "3g"), ("zi_su_ye", "使", "5片"), ("sheng_jiang", "使", "2片"), ("da_zao", "使", "1枚")]),
    ("ding_xiang_shi_di_tang", "丁香柿蒂汤", "理气剂", "温中降逆", "zheng_yin_mai_zhi",
     [("ding_xiang", "君", "6g"), ("shi_di", "臣", "9g"), ("ren_shen", "佐", "3g"), ("sheng_jiang", "使", "6g")]),
    ("xuan_fu_dai_zhe_tang", "旋覆代赭汤", "理气剂", "降逆化痰，益气和胃", "shang_han_lun",
     [("xuan_fu_hua", "君", "9g"), ("dai_zhe_shi", "臣", "9g"), ("ren_shen", "佐", "6g"),
      ("ban_xia", "佐", "9g"), ("sheng_jiang", "佐", "15g"), ("gan_cao", "使", "9g"), ("da_zao", "使", "4枚")]),
    ("tao_he_cheng_qi_tang", "桃核承气汤", "活血剂", "破血下瘀", "shang_han_lun",
     [("tao_ren", "君", "12g"), ("da_huang", "君", "12g"), ("gui_zhi", "臣", "6g"),
      ("mang_xiao", "佐", "6g"), ("gan_cao", "使", "6g")]),
    ("xue_fu_zhu_yu_tang", "血府逐瘀汤", "活血剂", "活血祛瘀，行气止痛", "yi_lin_gai_cuo",
     [("tao_ren", "君", "12g"), ("hong_hua", "君", "9g"), ("dang_gui", "臣", "9g"),
      ("sheng_di_huang", "臣", "9g"), ("chuan_xiong", "佐", "5g"), ("chi_shao", "佐", "6g"),
      ("niu_xi", "佐", "9g"), ("jie_geng", "佐", "5g"), ("chai_hu", "佐", "3g"),
      ("zhi_qiao", "佐", "6g"), ("gan_cao", "使", "3g")]),
    ("shao_fu_zhu_yu_tang", "少腹逐瘀汤", "活血剂", "活血祛瘀，温经止痛", "yi_lin_gai_cuo",
     [("xiao_hui_xiang", "君", "6g"), ("gan_jiang", "臣", "3g"), ("yan_hu_suo", "臣", "3g"),
      ("mo_yao", "佐", "3g"), ("dang_gui", "佐", "9g"), ("chuan_xiong", "佐", "6g"),
      ("rou_gui", "佐", "3g"), ("chi_shao", "佐", "6g"), ("pu_huang", "佐", "9g"), ("wu_ling_zhi", "使", "6g")]),
    ("shen_tong_zhu_yu_tang", "身痛逐瘀汤", "活血剂", "活血行气，祛瘀通络", "yi_lin_gai_cuo",
     [("qin_jiao", "君", "3g"), ("chuan_xiong", "君", "6g"), ("tao_ren", "臣", "9g"),
      ("hong_hua", "臣", "9g"), ("gan_cao", "使", "6g"), ("qiang_huo", "佐", "3g"),
      ("mo_yao", "佐", "6g"), ("dang_gui", "佐", "9g"), ("wu_ling_zhi", "佐", "6g"),
      ("xiang_fu", "佐", "3g"), ("niu_xi", "佐", "9g"), ("di_long", "使", "6g")]),
    ("bu_yang_huan_wu_tang", "补阳还五汤", "活血剂", "补气活血通络", "yi_lin_gai_cuo",
     [("huang_qi", "君", "120g"), ("dang_gui", "臣", "6g"), ("chi_shao", "佐", "5g"),
      ("di_long", "佐", "3g"), ("chuan_xiong", "佐", "3g"), ("hong_hua", "佐", "3g"), ("tao_ren", "佐", "3g")]),
    ("fu_yuan_huo_xue_tang", "复元活血汤", "活血剂", "活血祛瘀，疏肝通络", "yi_xue_fa_ming",
     [("chai_hu", "君", "15g"), ("gua_lou_gen", "臣", "9g"), ("dang_gui", "臣", "9g"),
      ("hong_hua", "佐", "6g"), ("gan_cao", "使", "6g"), ("chuan_shan_jia", "佐", "6g"),
      ("da_huang", "佐", "30g"), ("tao_ren", "佐", "9g")]),
    ("wen_jing_tang", "温经汤", "活血剂", "温经散寒，养血祛瘀", "jin_gui_yao_lue",
     [("wu_zhu_yu", "君", "9g"), ("gui_zhi", "臣", "6g"), ("dang_gui", "臣", "9g"),
      ("chuan_xiong", "佐", "6g"), ("bai_shao", "佐", "6g"), ("e_jiao", "佐", "6g"),
      ("mai_dong", "佐", "9g"), ("mu_dan_pi", "佐", "6g"), ("ren_shen", "佐", "6g"),
      ("gan_cao", "使", "6g"), ("sheng_jiang", "使", "6g"), ("ban_xia", "使", "6g")]),
    ("sheng_hua_tang", "生化汤", "活血剂", "养血祛瘀，温经止痛", "fu_qing_zhu_nv_ke",
     [("dang_gui", "君", "24g"), ("chuan_xiong", "臣", "9g"), ("tao_ren", "佐", "6g"),
      ("pao_jiang", "佐", "2g"), ("gan_cao", "使", "2g")]),
    ("shi_xiao_san", "失笑散", "活血剂", "活血祛瘀，散结止痛", "tai_ping_hui_min_he_ji_ju_fang",
     [("wu_ling_zhi", "君", "6g"), ("pu_huang", "臣", "6g")]),
    ("dan_shen_yin", "丹参饮", "活血剂", "活血祛瘀，行气止痛", "shi_fang_ge_kuo",
     [("dan_shen", "君", "30g"), ("tan_xiang", "臣", "3g"), ("sha_ren", "佐", "3g")]),
    ("xiao_huo_luo_dan", "小活络丹", "活血剂", "祛风除湿，化痰通络", "tai_ping_hui_min_he_ji_ju_fang",
     [("chuan_wu", "君", "6g"), ("cao_wu", "君", "6g"), ("di_long", "臣", "6g"),
      ("tian_nan_xing", "佐", "6g"), ("ru_xiang", "佐", "6g"), ("mo_yao", "佐", "6g")]),
    ("chuan_xiong_cha_tiao_san", "川芎茶调散", "治风剂", "疏风止痛", "tai_ping_hui_min_he_ji_ju_fang",
     [("chuan_xiong", "君", "12g"), ("bai_zhi", "臣", "6g"), ("qiang_huo", "臣", "6g"),
      ("xi_xin", "佐", "3g"), ("fang_feng", "佐", "4.5g"), ("jing_jie", "佐", "12g"),
      ("bo_he", "佐", "12g"), ("gan_cao", "使", "6g")]),
    ("da_qin_jiao_tang", "大秦艽汤", "治风剂", "祛风清热，养血活血", "su_wen_bing_ji_qi_yi_bao_ming_ji",
     [("qin_jiao", "君", "9g"), ("dang_gui", "臣", "6g"), ("chuan_xiong", "臣", "3g"),
      ("bai_shao", "佐", "3g"), ("du_huo", "佐", "6g"), ("fang_feng", "佐", "3g"),
      ("bai_zhi", "佐", "3g"), ("shu_di_huang", "佐", "3g"), ("fu_ling", "佐", "3g"),
      ("gan_cao", "使", "3g"), ("huang_qin", "佐", "3g"), ("shi_gao", "佐", "6g"),
      ("bai_zhu", "佐", "3g"), ("sheng_di_huang", "佐", "3g"), ("xi_xin", "使", "1.5g")]),
    ("xiao_feng_san", "消风散", "治风剂", "疏风养血，清热除湿", "wai_ke_zheng_zong",
     [("jing_jie", "君", "9g"), ("fang_feng", "君", "9g"), ("niu_bang_zi", "臣", "9g"),
      ("chan_tui", "臣", "9g"), ("cang_zhu", "佐", "9g"), ("ku_shen", "佐", "9g"),
      ("mu_tong", "佐", "5g"), ("shi_gao", "佐", "9g"), ("zhi_mu", "佐", "9g"),
      ("sheng_di_huang", "佐", "9g"), ("dang_gui", "佐", "9g"), ("hei_zhi_ma", "佐", "9g"), ("gan_cao", "使", "5g")]),
    ("ling_jiao_gou_teng_tang", "羚角钩藤汤", "治风剂", "凉肝息风，增液舒筋", "tong_su_shang_han_lun",
     [("ling_yang_jiao", "君", "4.5g"), ("gou_teng", "君", "9g"), ("sang_ye", "臣", "6g"),
      ("ju_hua", "臣", "9g"), ("sheng_di_huang", "佐", "15g"), ("bai_shao", "佐", "9g"),
      ("chuan_bei_mu", "佐", "12g"), ("zhu_ru", "佐", "15g"), ("fu_ling", "使", "9g"), ("gan_cao", "使", "3g")]),
    ("zhen_gan_xi_feng_tang", "镇肝息风汤", "治风剂", "镇肝息风，滋阴潜阳", "yi_xue_zhong_zhong_can_xi_lu",
     [("huai_niu_xi", "君", "30g"), ("dai_zhe_shi", "臣", "30g"), ("long_gu", "臣", "15g"),
      ("mu_li", "臣", "15g"), ("gui_ban", "佐", "15g"), ("bai_shao", "佐", "15g"),
      ("xuan_shen", "佐", "15g"), ("tian_dong", "佐", "15g"), ("chuan_lian_zi", "佐", "6g"),
      ("mai_ya", "佐", "15g"), ("yin_chen", "佐", "6g"), ("gan_cao", "使", "4.5g")]),
    ("tian_ma_gou_teng_yin", "天麻钩藤饮", "治风剂", "平肝息风，清热活血", "za_bing_zheng_zhi_xin_yi",
     [("tian_ma", "君", "9g"), ("gou_teng", "君", "12g"), ("shi_jue_ming", "臣", "18g"),
      ("zhi_zi", "佐", "9g"), ("huang_qin", "佐", "9g"), ("chuan_niu_xi", "佐", "12g"),
      ("du_zhong", "佐", "9g"), ("yi_mu_cao", "佐", "9g"), ("sang_ji_sheng", "佐", "9g"),
      ("ye_jiao_teng", "使", "9g"), ("fu_ling", "使", "9g")]),
    ("da_ding_feng_zhu", "大定风珠", "治风剂", "滋阴息风", "wen_bing_tiao_bian",
     [("bai_shao", "君", "18g"), ("e_jiao", "君", "9g"), ("gui_ban", "臣", "12g"),
      ("sheng_di_huang", "臣", "18g"), ("huo_ma_ren", "佐", "6g"), ("wu_wei_zi", "佐", "6g"),
      ("mu_li", "佐", "12g"), ("mai_dong", "佐", "18g"), ("gan_cao", "使", "12g"),
      ("bie_jia", "使", "12g"), ("ji_zi_huang", "使", "2枚")]),
    ("an_gong_niu_huang_wan", "安宫牛黄丸", "开窍剂", "清热开窍，豁痰解毒", "wen_bing_tiao_bian",
     [("niu_huang", "君", "30g"), ("shui_niu_jiao", "君", "60g"), ("she_xiang", "臣", "7.5g"),
      ("zhen_zhu", "佐", "30g"), ("zhu_sha", "佐", "30g"), ("xiong_huang", "佐", "30g"),
      ("huang_lian", "佐", "30g"), ("huang_qin", "佐", "30g"), ("zhi_zi", "佐", "30g"),
      ("yu_jin", "佐", "30g"), ("bing_pian", "使", "7.5g")]),
    ("zi_xue_dan", "紫雪丹", "开窍剂", "清热开窍，息风止痉", "wai_tai_mi_yao",
     [("shi_gao", "君", "1500g"), ("han_shui_shi", "君", "1500g"), ("hua_shi", "君", "1500g"),
      ("shui_niu_jiao", "臣", "150g"), ("ling_yang_jiao", "臣", "150g"), ("she_xiang", "佐", "37.5g"),
      ("xuan_shen", "佐", "500g"), ("mu_xiang", "佐", "150g"), ("chen_xiang", "佐", "150g"),
      ("ding_xiang", "佐", "30g"), ("sheng_ci_shi", "佐", "1500g"), ("hua_shi", "使", "1500g"), ("gan_cao", "使", "240g")]),
    ("su_he_xiang_wan", "苏合香丸", "开窍剂", "芳香开窍，行气止痛", "tai_ping_hui_min_he_ji_ju_fang",
     [("su_he_xiang", "君", "30g"), ("she_xiang", "君", "60g"), ("bing_pian", "臣", "30g"),
      ("an_xi_xiang", "臣", "60g"), ("mu_xiang", "佐", "60g"), ("tan_xiang", "佐", "60g"),
      ("chen_xiang", "佐", "60g"), ("ru_xiang", "佐", "30g"), ("ding_xiang", "佐", "60g"),
      ("xiang_fu", "佐", "60g"), ("bi_ba", "佐", "60g"), ("bai_zhu", "佐", "60g"),
      ("he_zi", "佐", "60g"), ("shui_niu_jiao", "使", "60g"), ("zhu_sha", "使", "60g")]),
    ("suan_zao_ren_tang", "酸枣仁汤", "安神剂", "养血安神，清热除烦", "jin_gui_yao_lue",
     [("suan_zao_ren", "君", "15g"), ("fu_ling", "臣", "6g"), ("zhi_mu", "臣", "6g"),
      ("chuan_xiong", "佐", "6g"), ("gan_cao", "使", "3g")]),
    ("tian_wang_bu_xin_dan", "天王补心丹", "安神剂", "滋阴养血，补心安神", "she_sheng_mi_pou",
     [("sheng_di_huang", "君", "120g"), ("ren_shen", "臣", "15g"), ("xuan_shen", "臣", "15g"),
      ("dan_shen", "佐", "15g"), ("fu_ling", "佐", "15g"), ("wu_wei_zi", "佐", "15g"),
      ("mai_dong", "佐", "15g"), ("tian_dong", "佐", "15g"), ("jie_geng", "使", "15g"),
      ("yuan_zhi", "佐", "15g"), ("dang_gui", "佐", "15g"), ("bai_zi_ren", "佐", "15g"), ("suan_zao_ren", "佐", "15g")]),
    ("gan_mai_da_zao_tang", "甘麦大枣汤", "安神剂", "养心安神，和中缓急", "jin_gui_yao_lue",
     [("gan_cao", "君", "9g"), ("xiao_mai", "臣", "15g"), ("da_zao", "使", "10枚")]),
    ("zhu_sha_an_shen_wan", "朱砂安神丸", "安神剂", "镇心安神，泻火养阴", "nei_wai_shang_bian_huo_lun",
     [("zhu_sha", "君", "15g"), ("huang_lian", "臣", "18g"), ("dang_gui", "佐", "8g"),
      ("sheng_di_huang", "佐", "8g"), ("gan_cao", "使", "16g")]),
    ("xiao_ji_yin_zi", "小蓟饮子", "止血剂", "凉血止血，利水通淋", "ji_sheng_fang",
     [("xiao_ji", "君", "15g"), ("ou_jie", "臣", "9g"), ("pu_huang", "臣", "9g"),
      ("hua_shi", "佐", "15g"), ("mu_tong", "佐", "9g"), ("sheng_di_huang", "佐", "30g"),
      ("dang_gui", "佐", "6g"), ("zhi_zi", "佐", "9g"), ("dan_zhu_ye", "使", "9g"), ("gan_cao", "使", "6g")]),
    ("huang_tu_tang", "黄土汤", "止血剂", "温阳健脾，养血止血", "jin_gui_yao_lue",
     [("zao_xin_tu", "君", "30g"), ("gan_cao", "臣", "9g"), ("gan_di_huang", "臣", "9g"),
      ("bai_zhu", "佐", "9g"), ("fu_zi", "佐", "9g"), ("e_jiao", "佐", "9g"), ("huang_qin", "使", "9g")]),
    ("huai_hua_san", "槐花散", "止血剂", "清肠止血，疏风行气", "pu_ji_ben_shi_fang",
     [("huai_hua", "君", "12g"), ("ce_bai_ye", "臣", "12g"), ("jing_jie", "佐", "6g"), ("zhi_qiao", "使", "6g")]),
    ("si_sheng_wan", "四生丸", "止血剂", "凉血止血", "fu_ren_liang_fang",
     [("sheng_ce_bai_ye", "君", "9g"), ("sheng_di_huang", "臣", "9g"), ("sheng_he_ye", "佐", "9g"), ("sheng_ai_ye", "使", "9g")]),
    ("ke_xue_fang", "咳血方", "止血剂", "清肝宁肺，凉血止血", "dan_xi_xin_fa",
     [("qing_dai", "君", "6g"), ("zhi_zi", "臣", "9g"), ("gua_lou_ren", "佐", "9g"),
      ("fu_hai_shi", "佐", "9g"), ("he_zi", "使", "6g")]),
    ("yu_ping_feng_san", "玉屏风散", "固涩剂", "益气固表止汗", "jiu_yuan_fang",
     [("huang_qi", "君", "30g"), ("bai_zhu", "臣", "60g"), ("fang_feng", "佐", "30g")]),
    ("mu_li_san", "牡蛎散", "固涩剂", "敛阴止汗，益气固表", "tai_ping_hui_min_he_ji_ju_fang",
     [("huang_qi", "君", "30g"), ("ma_huang_gen", "臣", "30g"), ("mu_li", "臣", "30g"), ("fu_xiao_mai", "使", "30g")]),
    ("si_shen_wan", "四神丸", "固涩剂", "温肾暖脾，固肠止泻", "zheng_zhi_zhun_sheng",
     [("bu_gu_zhi", "君", "12g"), ("wu_zhu_yu", "臣", "3g"), ("rou_dou_kou", "臣", "6g"),
      ("wu_wei_zi", "佐", "6g"), ("sheng_jiang", "使", "6g"), ("da_zao", "使", "6枚")]),
    ("jin_suo_gu_jing_wan", "金锁固精丸", "固涩剂", "补肾涩精", "yi_fang_ji_jie",
     [("sha_yuan_zi", "君", "60g"), ("qian_shi", "臣", "60g"), ("lian_xu", "臣", "60g"),
      ("long_gu", "佐", "30g"), ("mu_li", "佐", "30g"), ("lian_zi", "使", "30g")]),
    ("suo_quan_wan", "缩泉丸", "固涩剂", "温肾祛寒，缩尿止遗", "fu_ren_liang_fang",
     [("wu_yao", "君", "9g"), ("yi_zhi_ren", "臣", "9g"), ("shan_yao", "佐", "9g")]),
    ("gu_chong_tang", "固冲汤", "固涩剂", "益气健脾，固冲摄血", "yi_xue_zhong_zhong_can_xi_lu",
     [("bai_zhu", "君", "30g"), ("huang_qi", "君", "18g"), ("long_gu", "臣", "24g"),
      ("mu_li", "臣", "24g"), ("shan_zhu_yu", "佐", "24g"), ("bai_shao", "佐", "12g"),
      ("hai_piao_xiao", "佐", "12g"), ("qian_cao", "佐", "9g"), ("zong_lv_tan", "使", "6g"), ("wu_bei_zi", "使", "1.5g")]),
    ("wan_dai_tang", "完带汤", "固涩剂", "补脾疏肝，化湿止带", "fu_qing_zhu_nv_ke",
     [("bai_zhu", "君", "30g"), ("shan_yao", "君", "30g"), ("ren_shen", "臣", "6g"),
      ("bai_shao", "佐", "15g"), ("cang_zhu", "佐", "9g"), ("che_qian_zi", "佐", "9g"),
      ("gan_cao", "使", "3g"), ("chen_pi", "使", "2g"), ("jing_jie", "使", "2g"), ("chai_hu", "使", "2g")]),
    ("yi_huang_tang", "易黄汤", "固涩剂", "清利湿热，固带止遗", "fu_qing_zhu_nv_ke",
     [("shan_yao", "君", "30g"), ("qian_shi", "君", "30g"), ("huang_bai", "臣", "6g"),
      ("che_qian_zi", "佐", "3g"), ("bai_guo", "使", "10枚")]),
    ("xiao_ban_xia_tang", "小半夏汤", "祛痰剂", "和胃降逆，化痰止呕", "jin_gui_yao_lue",
     [("ban_xia", "君", "12g"), ("sheng_jiang", "臣", "15g")]),
    ("da_ban_xia_tang", "大半夏汤", "补益剂", "和胃降逆，益气润燥", "jin_gui_yao_lue",
     [("ban_xia", "君", "15g"), ("ren_shen", "臣", "9g"), ("feng_mi", "使", "20ml")]),
    ("gan_cao_xie_xin_tang", "甘草泻心汤", "和解剂", "益气和胃，消痞止呕", "shang_han_lun",
     [("gan_cao", "君", "12g"), ("huang_qin", "臣", "9g"), ("gan_jiang", "臣", "9g"),
      ("ban_xia", "佐", "9g"), ("da_zao", "使", "12枚"), ("huang_lian", "佐", "3g")]),
    ("ban_xia_xie_xin_tang", "半夏泻心汤", "和解剂", "寒热平调，消痞散结", "shang_han_lun",
     [("ban_xia", "君", "12g"), ("huang_qin", "臣", "9g"), ("gan_jiang", "臣", "9g"),
      ("ren_shen", "佐", "9g"), ("gan_cao", "使", "9g"), ("huang_lian", "佐", "3g"), ("da_zao", "使", "12枚")]),
    ("sheng_jiang_xie_xin_tang", "生姜泻心汤", "和解剂", "和胃消痞，宣散水气", "shang_han_lun",
     [("sheng_jiang", "君", "12g"), ("gan_jiang", "臣", "3g"), ("ban_xia", "臣", "9g"),
      ("huang_qin", "佐", "9g"), ("huang_lian", "佐", "3g"), ("ren_shen", "佐", "9g"),
      ("gan_cao", "使", "9g"), ("da_zao", "使", "12枚")]),
    ("huang_lian_tang", "黄连汤", "和解剂", "平调寒热，和胃降逆", "shang_han_lun",
     [("huang_lian", "君", "9g"), ("gan_jiang", "臣", "9g"), ("gui_zhi", "臣", "9g"),
      ("ban_xia", "佐", "9g"), ("ren_shen", "佐", "6g"), ("da_zao", "使", "6枚"), ("gan_cao", "使", "6g")]),
    ("xiao_xian_xiong_tang", "小陷胸汤", "祛痰剂", "清热化痰，宽胸散结", "shang_han_lun",
     [("huang_lian", "君", "6g"), ("ban_xia", "臣", "12g"), ("gua_lou", "佐", "30g")]),
    ("gua_lou_xie_bai_bai_jiu_tang", "瓜蒌薤白白酒汤", "理气剂", "通阳散结，行气祛痰", "jin_gui_yao_lue",
     [("gua_lou", "君", "12g"), ("xie_bai", "臣", "12g"), ("bai_jiu", "使", "适量")]),
    ("gua_lou_xie_bai_ban_xia_tang", "瓜蒌薤白半夏汤", "理气剂", "通阳散结，祛痰宽胸", "jin_gui_yao_lue",
     [("gua_lou", "君", "12g"), ("xie_bai", "臣", "9g"), ("ban_xia", "佐", "12g"), ("bai_jiu", "使", "适量")]),
    ("dang_gui_liu_huang_tang", "当归六黄汤", "清热剂", "滋阴泻火，固表止汗", "lan_shi_mi_cang",
     [("dang_gui", "君", "6g"), ("sheng_di_huang", "君", "6g"), ("shu_di_huang", "君", "6g"),
      ("huang_lian", "臣", "6g"), ("huang_qin", "臣", "6g"), ("huang_bai", "臣", "6g"), ("huang_qi", "使", "12g")]),
    ("qing_hao_bie_jia_tang", "青蒿鳖甲汤", "清热剂", "养阴透热", "wen_bing_tiao_bian",
     [("qing_hao", "君", "6g"), ("bie_jia", "君", "15g"), ("sheng_di_huang", "臣", "12g"),
      ("zhi_mu", "佐", "6g"), ("mu_dan_pi", "佐", "9g")]),
    ("qin_jiao_bie_jia_san", "秦艽鳖甲散", "清热剂", "滋阴养血，清热除蒸", "wei_shi_jia_cang_fang",
     [("di_gu_pi", "君", "30g"), ("chai_hu", "君", "30g"), ("bie_jia", "臣", "30g"),
      ("qin_jiao", "臣", "15g"), ("zhi_mu", "佐", "15g"), ("dang_gui", "使", "15g")]),
    ("dang_gui_si_ni_jia_wu_zhu_yu_sheng_jiang", "当归四逆加吴茱萸生姜汤", "温里剂", "温经散寒", "shang_han_lun",
     [("dang_gui", "君", "12g"), ("gui_zhi", "臣", "9g"), ("bai_shao", "臣", "9g"),
      ("xi_xin", "佐", "3g"), ("gan_cao", "使", "6g"), ("tong_cao", "佐", "6g"),
      ("da_zao", "使", "8枚"), ("wu_zhu_yu", "佐", "6g"), ("sheng_jiang", "佐", "15g")]),
    ("ma_huang_fu_zi_xi_xin_tang", "麻黄附子细辛汤", "解表剂", "助阳解表", "shang_han_lun",
     [("ma_huang", "君", "6g"), ("fu_zi", "臣", "9g"), ("xi_xin", "佐", "3g")]),
    ("ma_huang_fu_zi_gan_cao_tang", "麻黄附子甘草汤", "解表剂", "助阳解表", "shang_han_lun",
     [("ma_huang", "君", "6g"), ("fu_zi", "臣", "9g"), ("gan_cao", "使", "6g")]),
    ("gui_zhi_jia_ge_gen_tang", "桂枝加葛根汤", "解表剂", "解肌舒经", "shang_han_lun",
     [("ge_gen", "君", "12g"), ("gui_zhi", "臣", "6g"), ("bai_shao", "臣", "6g"),
      ("sheng_jiang", "佐", "9g"), ("da_zao", "使", "6枚"), ("gan_cao", "使", "6g")]),
    ("gui_zhi_jia_hou_po_xing_zi_tang", "桂枝加厚朴杏子汤", "解表剂", "解肌降气", "shang_han_lun",
     [("gui_zhi", "君", "9g"), ("bai_shao", "臣", "9g"), ("hou_po", "佐", "6g"),
      ("xing_ren", "佐", "6g"), ("sheng_jiang", "佐", "9g"), ("da_zao", "使", "6枚"), ("gan_cao", "使", "6g")]),
    ("gui_zhi_qu_shao_yao_tang", "桂枝去芍药汤", "解表剂", "解肌通阳", "shang_han_lun",
     [("gui_zhi", "君", "9g"), ("sheng_jiang", "臣", "9g"), ("da_zao", "使", "6枚"), ("gan_cao", "使", "6g")]),
    ("gui_zhi_jia_fu_zi_tang", "桂枝加附子汤", "解表剂", "扶阳固表", "shang_han_lun",
     [("gui_zhi", "君", "9g"), ("bai_shao", "臣", "9g"), ("sheng_jiang", "佐", "9g"),
      ("da_zao", "使", "6枚"), ("gan_cao", "使", "6g"), ("fu_zi", "佐", "9g")]),
    ("xiao_jian_zhong_jia_huang_qi", "黄芪建中汤", "温里剂", "温中补气", "jin_gui_yao_lue",
     [("yi_tang", "君", "30g"), ("gui_zhi", "臣", "9g"), ("bai_shao", "臣", "18g"),
      ("sheng_jiang", "佐", "9g"), ("da_zao", "使", "6枚"), ("gan_cao", "使", "6g"), ("huang_qi", "佐", "15g")]),
    ("dang_gui_jian_zhong_tang", "当归建中汤", "温里剂", "温中补血", "qian_jin_yi_fang",
     [("yi_tang", "君", "30g"), ("gui_zhi", "臣", "9g"), ("bai_shao", "臣", "18g"),
      ("sheng_jiang", "佐", "9g"), ("da_zao", "使", "6枚"), ("gan_cao", "使", "6g"), ("dang_gui", "佐", "12g")]),
    ("fu_zi_li_zhong_wan", "附子理中丸", "温里剂", "温阳祛寒，补气健脾", "san_yin_ji_yi_bing_zheng_fang_lun",
     [("fu_zi", "君", "9g"), ("ren_shen", "臣", "9g"), ("bai_zhu", "佐", "9g"),
      ("gan_jiang", "佐", "9g"), ("gan_cao", "使", "9g")]),
    ("gui_zhi_ren_shen_tang", "桂枝人参汤", "温里剂", "温中解表", "shang_han_lun",
     [("gui_zhi", "君", "12g"), ("gan_cao", "臣", "12g"), ("bai_zhu", "佐", "9g"),
      ("ren_shen", "佐", "9g"), ("gan_jiang", "使", "9g")]),
    ("tong_xie_yao_fang", "痛泻要方", "和解剂", "补脾柔肝，祛湿止泻", "dan_xi_xin_fa",
     [("bai_zhu", "君", "9g"), ("bai_shao", "臣", "6g"), ("chen_pi", "佐", "4.5g"), ("fang_feng", "使", "6g")]),
    ("chai_hu_shu_gan_san", "柴胡疏肝散", "理气剂", "疏肝行气，活血止痛", "jing_yue_quan_shu",
     [("chai_hu", "君", "6g"), ("xiang_fu", "臣", "5g"), ("chuan_xiong", "臣", "5g"),
      ("chen_pi", "佐", "6g"), ("zhi_qiao", "佐", "5g"), ("bai_shao", "佐", "5g"), ("gan_cao", "使", "3g")]),
    ("si_mo_tang", "四磨汤", "理气剂", "行气降逆，宽胸散结", "ji_sheng_fang",
     [("ren_shen", "君", "6g"), ("bing_lang", "臣", "9g"), ("chen_xiang", "佐", "6g"), ("wu_yao", "使", "9g")]),
    ("mu_xiang_bing_lang_wan", "木香槟榔丸", "消食剂", "行气导滞，攻积泄热", "ru_men_shi_qin",
     [("mu_xiang", "君", "6g"), ("bing_lang", "君", "6g"), ("qing_pi", "臣", "6g"),
      ("chen_pi", "臣", "6g"), ("e_zhu", "佐", "6g"), ("huang_lian", "佐", "6g"),
      ("huang_bai", "佐", "6g"), ("da_huang", "佐", "9g"), ("xiang_fu", "佐", "6g"), ("qian_niu_zi", "使", "12g")]),
    ("zhi_zhu_wan", "枳术丸", "消食剂", "健脾消痞", "nei_wai_shang_bian_huo_lun",
     [("zhi_shi", "君", "30g"), ("bai_zhu", "臣", "60g")]),
    ("wu_mei_wan", "乌梅丸", "驱虫剂", "温脏安蛔", "shang_han_lun",
     [("wu_mei", "君", "30g"), ("xi_xin", "臣", "6g"), ("gan_jiang", "臣", "9g"),
      ("huang_lian", "佐", "12g"), ("dang_gui", "佐", "6g"), ("fu_zi", "佐", "6g"),
      ("hua_jiao", "佐", "4g"), ("gui_zhi", "佐", "6g"), ("ren_shen", "佐", "6g"), ("huang_bai", "使", "6g")]),
    ("hua_chong_wan", "化虫丸", "驱虫剂", "杀虫消积", "tai_ping_hui_min_he_ji_ju_fang",
     [("he_shi", "君", "30g"), ("bing_lang", "臣", "30g"), ("ku_lian_pi", "臣", "30g"),
      ("qian_niu_zi", "佐", "30g"), ("shi_jun_zi", "佐", "30g"), ("wu_yi", "使", "15g")]),
]


def main():
    existing = set()
    raw_path = ROOT / "data" / "formulas_raw.json"
    if raw_path.exists():
        for f in json.loads(raw_path.read_text(encoding="utf-8")):
            existing.add(f.get("key"))
    out = []
    for row in RAW:
        item = F(*row)
        if item["key"] in existing:
            continue
        out.append(item)
        existing.add(item["key"])
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {len(out)} formulas -> {OUT}")


if __name__ == "__main__":
    main()
